### PR TITLE
Upgrade to Angular 9

### PR DESCRIPTION
**Pull request by shahmirn**
Upgrade to Angular 9; followed same pattern as ngx-color-picker, which is to switch to use the Angular CLI to create a library project.

### CODE REVIEW

**Comment by shahmirn** [comment]
The scripts in package.json changed a bit;

To publish:
- Update the version in the different package.json and package-lock.json files
- npm run prepare
- npm run publish

**Comment by greg7859** [comment]
Thank you to contribute to this project!

**Comment by shahmirn** [comment]
@greg7859 No problem! Could you publish a new version to npm?

**Comment by greg7859** [comment]
> @greg7859 No problem! Could you publish a new version to npm?

The new version was published a few minutes ago. Tell me if you meet some problems.

**Pull request merged**
