### PR TITLE
Updating the Angular 13.3 version

### PR DESCRIPTION
**Pull request by rodrigokamada**
Hi,

I'm getting the below error when I'm using Angular version 13.3.3.

```powershell
npm ERR! Found: @angular/common@13.3.3
npm ERR! node_modules/@angular/common
npm ERR!   @angular/common@"~13.3.3" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/common@"~13.0.0" from ngx-icon-picker@1.8.0
npm ERR! node_modules/ngx-icon-picker
npm ERR!   ngx-icon-picker@"^1.8.0" from the root project
```

So, I'm updating Angular libraries in this PR.

Thank you,
Rodrigo Kamada

### CODE REVIEW

**Comment by greg7859** [comment]
Thanks you for this PR.

To avoid any problem in the furture, I think the version should be ^13.0.0 (minor version supported)

**Comment by rodrigokamada** [comment]
Hi @greg7859!

Thank you for your reply.

But don't you think it would be an evolution?

Will people who want to use the latest version of Angular have to deal with this dependency conflict?

Thank you,
Rodrigo Kamada

**Comment by Bentipa** [comment]
Is this already pushed to npm?

**Comment by greg7859** [comment]
The package was deployed this day: 1.9.1

**Pull request merged**
